apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mission-ingress
  namespace: compte
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: 
      http:
        paths:
        - path: /v1/mission
          backend:
            serviceName: compte-service
            servicePort: 80