apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: module-ingress
  namespace: compte
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: 
      http:
        paths:
        - path: /v1/module
          backend:
            serviceName: compte-service
            servicePort: 80